import React, { useState } from 'react';
import { Target, Trophy, Cpu, Server, Smartphone, HardDrive, Clock, Workflow, Brain, Layers, Bot, ChevronDown, ChevronUp } from 'lucide-react';

export default function AdvisoryTab({ advisory, isLlmPowered = false }) {
  const [showCoT, setShowCoT] = useState(true);

  if (!advisory) {
    return (
      <div className="py-12 text-center text-slate-400">
        No advisory strategy generated for this topic yet.
      </div>
    );
  }

  const why_matched = advisory.why_matched;
  const winning_edge = advisory.winning_edge || advisory.winning_novelty_edge;
  const tech_stack = advisory.tech_stack || advisory.recommended_tech_stack || {};
  const roadmap_36h = advisory.roadmap_36h || advisory.feasibility_roadmap || [];
  const chain_of_thought = advisory.chain_of_thought || [];

  const getActorIcon = (actor = '') => {
    const a = actor.toLowerCase();
    if (a.includes('nlp') || a.includes('spacy') || a.includes('parser')) {
      return <Brain className="w-3.5 h-3.5 text-purple-400" />;
    }
    if (a.includes('academic') || a.includes('patent') || a.includes('crawler')) {
      return <Layers className="w-3.5 h-3.5 text-blue-400" />;
    }
    if (a.includes('architecture')) {
      return <Cpu className="w-3.5 h-3.5 text-cyan-400" />;
    }
    return <Bot className="w-3.5 h-3.5 text-emerald-400" />;
  };

  return (
    <div className="space-y-6">
      {/* LLM vs Rule Indicator */}
      {isLlmPowered && (
        <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-xs text-emerald-300 flex items-center justify-between">
          <span>✨ Dynamically generated by active LLM engine tailored to this problem statement and retrieved prior art.</span>
        </div>
      )}

      {/* Top Advisory Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Why Matched */}
        <div className="p-5 rounded-2xl bg-dark-900/60 border border-slate-800 flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400 shrink-0">
            <Target className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-white mb-1.5">Why This Matches Your Idea</h4>
            <p className="text-xs text-slate-300 leading-relaxed">
              {why_matched || 'Matches closely based on semantic intent and domain concepts.'}
            </p>
          </div>
        </div>

        {/* Winning Edge */}
        <div className="p-5 rounded-2xl bg-gradient-to-br from-dark-900 to-dark-850 border border-amber-500/30 flex items-start gap-4 shadow-lg shadow-amber-500/5">
          <div className="w-10 h-10 rounded-xl bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-400 shrink-0">
            <Trophy className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <h4 className="text-sm font-bold text-white">Judge Winning Edge</h4>
              <span className="px-2 py-0.2 rounded-full text-[10px] font-semibold bg-amber-500/15 text-amber-300 border border-amber-500/30">
                Novelty Factor
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              {winning_edge || 'Unique real-time edge computing and offline fallback capability.'}
            </p>
          </div>
        </div>
      </div>

      {/* Recommended Tech Stack */}
      <div className="p-5 rounded-2xl bg-dark-900/60 border border-slate-800">
        <h4 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
          <Cpu className="w-4 h-4 text-cyan-400" />
          Recommended Architecture & Technology Stack
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {/* AI / ML Engine */}
          <div className="p-3.5 rounded-xl bg-dark-950/70 border border-slate-800">
            <span className="text-[11px] font-semibold text-cyan-400 block mb-1 flex items-center gap-1.5">
              <Cpu className="w-3.5 h-3.5" /> AI / ML Engine
            </span>
            <p className="text-xs text-slate-200 font-medium">
              {tech_stack.ai_ml || 'PyTorch / ONNX Runtime / Ultralytics YOLO'}
            </p>
          </div>

          {/* Backend & API */}
          <div className="p-3.5 rounded-xl bg-dark-950/70 border border-slate-800">
            <span className="text-[11px] font-semibold text-blue-400 block mb-1 flex items-center gap-1.5">
              <Server className="w-3.5 h-3.5" /> Backend & API
            </span>
            <p className="text-xs text-slate-200 font-medium">
              {tech_stack.backend || 'FastAPI / PostgreSQL / Redis / Docker'}
            </p>
          </div>

          {/* Frontend UI / Mobile */}
          <div className="p-3.5 rounded-xl bg-dark-950/70 border border-slate-800">
            <span className="text-[11px] font-semibold text-purple-400 block mb-1 flex items-center gap-1.5">
              <Smartphone className="w-3.5 h-3.5" /> Frontend UI / Mobile
            </span>
            <p className="text-xs text-slate-200 font-medium">
              {tech_stack.frontend || 'React 18 + Tailwind CSS / Flutter Mobile'}
            </p>
          </div>

          {/* Hardware / IoT */}
          <div className="p-3.5 rounded-xl bg-dark-950/70 border border-slate-800">
            <span className="text-[11px] font-semibold text-emerald-400 block mb-1 flex items-center gap-1.5">
              <HardDrive className="w-3.5 h-3.5" /> Hardware / IoT
            </span>
            <p className="text-xs text-slate-200 font-medium">
              {tech_stack.hardware_iot || 'Raspberry Pi 4 / ESP32 Microcontroller / LoRa'}
            </p>
          </div>
        </div>
      </div>

      {/* 36-Hour Hackathon MVP Roadmap */}
      <div className="p-5 rounded-2xl bg-dark-900/60 border border-slate-800">
        <h4 className="text-sm font-bold text-white mb-4 flex items-center gap-2">
          <Clock className="w-4 h-4 text-cyan-400" />
          36-Hour Hackathon MVP Sprint Roadmap
        </h4>

        <div className="space-y-3">
          {roadmap_36h && roadmap_36h.length > 0 ? (
            roadmap_36h.map((phase, idx) => (
              <div key={idx} className="flex items-start gap-3.5 p-3 rounded-xl bg-dark-950/60 border border-slate-800/80">
                <span className="px-2.5 py-1 rounded-md text-xs font-mono font-bold bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 shrink-0">
                  {phase.hours || phase.phase || `Phase ${idx + 1}`}
                </span>
                <div>
                  <h5 className="text-xs font-bold text-white mb-0.5">{phase.focus || phase.title || phase.phase || `Sprint ${idx + 1}`}</h5>
                  <p className="text-xs text-slate-300 leading-relaxed">{phase.tasks || phase.deliverable || phase.milestone}</p>
                </div>
              </div>
            ))
          ) : (
            <p className="text-xs text-slate-400">Roadmap not available.</p>
          )}
        </div>
      </div>

      {/* Strategic Chain of Thought (NLP + Prior Art + Architecture) */}
      {chain_of_thought && chain_of_thought.length > 0 && (
        <div className="p-5 rounded-2xl bg-gradient-to-r from-dark-900 via-dark-850 to-dark-900 border border-cyan-500/30 shadow-xl shadow-cyan-500/5">
          <div className="flex items-center justify-between pb-3 mb-4 border-b border-white/5">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-cyan-500/15 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
                <Workflow className="w-4 h-4" />
              </div>
              <div>
                <h4 className="text-sm font-bold text-white flex items-center gap-2">
                  Cognitive Reasoning Trace (Chain of Thought)
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-300 border border-cyan-500/20 font-mono">
                    {chain_of_thought.length} Steps
                  </span>
                </h4>
                <p className="text-[11px] text-slate-400">
                  Step-by-step technical deduction connecting NLP parsing, patent gaps, and 36h feasibility
                </p>
              </div>
            </div>

            <button
              onClick={() => setShowCoT(!showCoT)}
              className="flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-semibold text-cyan-300 bg-dark-800 hover:bg-dark-750 border border-cyan-500/20 transition-colors cursor-pointer"
            >
              <span>{showCoT ? 'Collapse' : 'Expand'}</span>
              {showCoT ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            </button>
          </div>

          {showCoT && (
            <div className="space-y-3">
              {chain_of_thought.map((step, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-xl bg-dark-950/70 border border-slate-800/90 hover:border-cyan-500/30 transition-colors"
                >
                  <div className="flex flex-wrap items-center justify-between gap-2 mb-1.5">
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-white/5 text-slate-300 border border-white/10">
                        Step {step.step || idx + 1}
                      </span>
                      <h5 className="text-xs sm:text-sm font-semibold text-white">
                        {step.stage || `Stage ${idx + 1}`}
                      </h5>
                    </div>

                    {step.actor && (
                      <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-semibold bg-cyan-500/10 text-cyan-300 border border-cyan-500/20">
                        {getActorIcon(step.actor)}
                        {step.actor}
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-slate-300 leading-relaxed mb-2 font-normal">
                    {step.thought}
                  </p>

                  {step.tags && Array.isArray(step.tags) && step.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1.5 pt-1.5 border-t border-white/5">
                      {step.tags.map((t, tIdx) => (
                        <span
                          key={tIdx}
                          className="px-2 py-0.5 rounded text-[10px] font-medium bg-dark-800 text-slate-400 border border-slate-700/40"
                        >
                          {t}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
